version: "3.2"
services:
  app:
    command: node src/server.js
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - published: ${APP_PORT:-3000}
        target: 3000
    volumes:
      - .:/app/
    env_file:
      - .env
    environment:
      JWT_SECRET: ${JWT_SECRET}
    links:
      - mongo  
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'